# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_resource',
            field=models.FloatField(default=0, null=True, verbose_name='Баланс'),
        ),
    ]
