# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0002_auto_20180225_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deposits',
        ),
    ]
