# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0004_customuser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, max_length=1000, null=True, verbose_name='Процент')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='deposits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='take_access.Deposits'),
        ),
        migrations.AddField(
            model_name='deposits',
            name='sum',
            field=models.FloatField(default=0, max_length=500000, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_resource',
            field=models.FloatField(default=0, max_length=500000, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='deposits',
            name='profit',
            field=models.ManyToManyField(to='take_access.Profit', verbose_name='Профит'),
        ),
    ]
