# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0005_auto_20180223_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deposits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='take_access.Deposits', verbose_name='Депозиты'),
        ),
    ]
