# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0006_auto_20180223_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposits',
            new_name='DepositsModel',
        ),
        migrations.RenameModel(
            old_name='Profit',
            new_name='ProfitModel',
        ),
        migrations.RenameField(
            model_name='depositsmodel',
            old_name='sum',
            new_name='sum_num',
        ),
    ]
