# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0007_auto_20180325_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_resource',
        ),
    ]
