# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0008_remove_customuser_account_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='partners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referal_user', to=settings.AUTH_USER_MODEL, verbose_name='Рефералы'),
        ),
    ]
