# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_access', '0010_auto_20180329_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referal_user', to=settings.AUTH_USER_MODEL, verbose_name='Рефералы'),
        ),
    ]
