# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
    ]
