# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 13:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import how_to_start.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowToStartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('cover_pic', models.ImageField(blank=True, upload_to=how_to_start.models.upload_path, verbose_name='Картинка')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Как начать',
            },
        ),
    ]
