# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howtostartmodel',
            options={'verbose_name': 'Как начать', 'verbose_name_plural': 'Как начать'},
        ),
    ]
