# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay_off_requests', '0003_auto_20180328_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoffmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payoff_related_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
