# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_off_requests', '0004_payoffmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoffmodel',
            name='wallet',
            field=models.CharField(default='', max_length=50, verbose_name='Номер Карты/Кошелька'),
        ),
    ]
