# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-date_added'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
