# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 14:59
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180224_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='announce',
            field=ckeditor.fields.RichTextField(verbose_name='Предпросмотр'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to=news.models.upload_path, verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Черновик')], default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='meta_description',
            field=models.TextField(null=True, verbose_name='СEO/Мета описание'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='meta_title',
            field=models.CharField(max_length=250, null=True, verbose_name='СЕО/Мета название'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
