# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180224_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
