# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecharge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
