# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
