# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20180306_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
    ]
