# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 15:56
from __future__ import unicode_literals

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20180306_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=about.models.upload_path, verbose_name='Документы')),
            ],
        ),
    ]
