# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_documentsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsmodel',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
