# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 09:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(choices=[('BTC', 'BitCoin'), ('LTC', 'LiteCoin'), ('ETH', 'Etherium'), ('DSH', 'Dash'), ('XRP', 'Ripple')], max_length=3, verbose_name='Валюта')),
                ('amount', models.FloatField(default=0, max_length=500000, verbose_name='Капитал')),
            ],
            options={
                'verbose_name_plural': 'Депозиты',
                'verbose_name': 'Депозит',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('percent', models.FloatField(default=0, max_length=1000, null=True, verbose_name='Процент')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Выгоды',
                'verbose_name': 'Выгода',
            },
        ),
        migrations.AddField(
            model_name='depositsmodel',
            name='profit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='deposits.ProfitModel', verbose_name='Выгода'),
        ),
    ]
