# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsmodel',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now),
        ),
    ]
