# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_auto_20180225_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsmodel',
            name='slug',
            field=models.SlugField(blank=True, default='<function now at 0x7fdb11565d90>'),
        ),
    ]
