# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0008_auto_20180226_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='profitmodel',
            name='amount_ceil',
            field=models.CharField(default=0, max_length=150, verbose_name='Сумма депозита до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitmodel',
            name='amount_floor',
            field=models.CharField(default=0, max_length=150, verbose_name='Сумма депозита от'),
            preserve_default=False,
        ),
    ]
