# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0010_auto_20180306_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsmodel',
            name='title',
        ),
    ]
