# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0011_remove_depositsmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAllDepositsInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.IntegerField(default=0, verbose_name='Всего депозитов')),
                ('payed_off', models.IntegerField(default=0, verbose_name='Всего выведено')),
                ('active_deposits', models.IntegerField(default=0, verbose_name='Сумма активных депозитов')),
                ('partner_sum', models.IntegerField(default=0, verbose_name='Партнерка')),
            ],
        ),
        migrations.AddField(
            model_name='depositsmodel',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Активный'), (False, 'Не активный')], default=True, max_length=10, verbose_name='Статус'),
        ),
    ]
